In [44]:
import pandas as pd
import numpy as np
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from category_encoders import OrdinalEncoder, OneHotEncoder

from sklearn.metrics import accuracy_score, classification_report, roc_auc_score, plot_roc_curve
from sklearn.pipeline import make_pipeline
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
url = 'http://localhost:8888/edit/Dengue_features_train/dengue_labels_train.csv'
dengue_labels_train = pd.read_csv('Dengue_features_train/dengue_labels_train.csv')
dengue_features_train = pd.read_csv('Dengue_features_train/dengue_features_train.csv')
dengue_features_test = pd.read_csv('Dengue_features_train/dengue_features_test (1).csv')
submission_format = pd.read_csv('Dengue_features_train/submission_format (4).csv')

# Introduction

Dengue fever is a mosquito-borne disease that occurs in tropical and sub-tropical parts of the world. In mild cases, symptoms are similar to the flu: fever, rash, and muscle and joint pain. In severe cases, dengue fever can cause severe bleeding, low blood pressure, and even death.

Because it is carried by mosquitoes, the transmission dynamics of dengue are related to climate variables such as temperature and precipitation. Although the relationship to climate is complex, a growing number of scientists argue that climate change is likely to produce distributional shifts that will have significant public health implications worldwide.

In recent years dengue fever has been spreading. Historically, the disease has been most prevalent in Southeast Asia and the Pacific islands. These days many of the nearly half billion cases per year are occurring in Latin America.

# Research Background

The data comes from multiple sources aimed at supporting the Predict the Next Pandemic Initiative. Dengue surveillance data is provided by the U.S. Centers for Disease Control and prevention, as well as the Department of Defense's Naval Medical Research Unit 6 and the Armed Forces Health Surveillance Center, in collaboration with the Peruvian government and U.S. universities. Environmental and climate data is provided by the National Oceanic and Atmospheric Administration (NOAA), an agency of the U.S. Department of Commerce.

# Problem Statement(Prediction)

The problem statement (goal) is to predict the total_cases label for each (city, year, week of the year) in the test set. There are two cities, San Juan and Iquitos, with test data for each city spanning 5 and 3 years respectively. This will make one submission that contains predictions for both cities. The data for each city have been concatenated along with a city column indicating the source: sj for San Juan and iq for Iquitos. The test set is a pure future hold-out, meaning the test data are sequential and non-overlapping with any of the training data. Throughout, missing values have been filled as NaNs.

# Features and Observations

Obeservation and Features of datsets
List of features
Performance metric
Mean absolute error
Submission Format Format
The features in this dataset City and date indicators city –
City abbreviations:
sj for San Juan and iq for Iquitos
week_start_date –Date given in yyyy-mm-dd format
NOAA's GHCN daily climate data weather station measurements station_
max_temp_c – Maximum temperature station_
min_temp_c – Minimum temperature station_
avg_temp_c – Average temperature station_
precip_mm – Total precipitation station_
diur_temp_rng_c – Diurnal temperature range PERSIANN satellite precipitation measurements (0.25x0.25 degree scale)
precipitation_amt_mm – Total precipitation NOAA's NCEP Climate Forecast System Reanalysis measurements (0.5x0.5 degree scale) reanalysis
sat_precip_amt_mm –Total precipitation reanalysis_
dew_point_temp_k – Mean dew point temperature reanalysis_
air_temp_k – Mean air temperature reanalysis_
relative_humidity_percent – Mean relative humidity reanalysis_specific_humidity_
g_per_kg – Mean specific humidity reanalysis_
precip_amt_kg_per_m2 – Total precipitation reanalysis_
max_air_temp_k – Maximum air temperature reanalysis_
min_air_temp_k –Minimum air temperature reanalysis_
avg_temp_k – Average air temperature reanalysis_
tdtr_k –Diurnal temperature range Satellite vegetation -
Normalized difference vegetation index (NDVI) -
NOAA's CDR Normalized Difference Vegetation Index (0.5x0.5 degree scale) measurements
ndvi_se – Pixel southeast of city centroid
ndvi_sw – Pixel southwest of city centroid
ndvi_ne –Pixel northeast of city centroid
ndvi_nw – Pixel northwest of city centroid

# Summary of the Dataset

The current epidemics of dengue fever diseases have been a burning issue. Hence there is need to resolve The statical significant and relationship between climate and dengue dynamics can improve research initiatives and resource allocation to help fight life-threatening pandemics.
 Hence we will be able to predict the number of dengue cases each week (in each location) based on environmental variables describing changes in temperature, precipitation, vegetation, and more.

### METHODOLOGY

In [45]:
from category_encoders import OrdinalEncoder, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np 
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.tree import export_graphviz
import graphviz
from sklearn.feature_selection import SelectKBest
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.model_selection import validation_curve
from sklearn.tree import DecisionTreeRegressor
from numpy.random import permutation
from sklearn.inspection import permutation_importance
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBClassifier
#from pandas_profiling import ProfileReport

In [46]:

url = 'http://localhost:8888/edit/Dengue_features_train/dengue_labels_train.csv'
dengue_labels_train = pd.read_csv('Dengue_features_train/dengue_labels_train.csv')
dengue_features_train = pd.read_csv('Dengue_features_train/dengue_features_train.csv')
dengue_features_test = pd.read_csv('Dengue_features_train/dengue_features_test (1).csv')
submission_format = pd.read_csv('Dengue_features_train/submission_format (4).csv')

In [47]:
df= pd.concat([(dengue_labels_train),
          (dengue_features_train ),
         (dengue_features_test)]
).set_index('week_start_date')

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3328 entries, nan to 2013-06-25
Data columns (total 24 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   city                                   3328 non-null   object
 1   year                                   3328 non-null   int64
 2   weekofyear                             3328 non-null   int64
 3   total_cases                            1456 non-null   float64
 4   ndvi_ne                                1635 non-null   float64
 5   ndvi_nw                                1809 non-null   float64
 6   ndvi_se                                1849 non-null   float64
 7   ndvi_sw                                1849 non-null   float64
 8   precipitation_amt_mm                   1857 non-null   float64
 9   reanalysis_air_temp_k                  1860 non-null   float64
 10  reanalysis_avg_temp_k                  1860 non-null   float64
 11  reanalysis_dew_point_temp_k            1860 non-null   float64
 12  reanalysis_max_air_temp_k              1860 non-null   float64
 13  reanalysis_min_air_temp_k              1860 non-null   float64
 14  reanalysis_precip_amt_kg_per_m2        1860 non-null   float64
 15  reanalysis_relative_humidity_percent   1860 non-null   float64
 16  reanalysis_sat_precip_amt_mm           1857 non-null   float64
 17  reanalysis_specific_humidity_g_per_kg  1860 non-null   float64
 18  reanalysis_tdtr_k                      1860 non-null   float64
 19  station_avg_temp_c                     1817 non-null   float64
 20  station_diur_temp_rng_c                1817 non-null   float64
 21  station_max_temp_c                     1849 non-null   float64
 22  station_min_temp_c                     1849 non-null   float64
 23  station_precip_mm                      1845 non-null   float64
dtypes: float64(21), int64(2), object(1)
memory usage: 650.0+ KB

In [49]:
df

,city,year,weekofyear,total_cases,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm
week_start_date,,,,,,,,,,,,,,,,,,,,,
NaN,sj,1990,18,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,sj,1990,19,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,sj,1990,20,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,sj,1990,21,3.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,sj,1990,22,6.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013-05-28,iq,2013,22,NaN,0.301471,0.380029,0.280629,0.383186,41.12,297.774286,...,67.60,89.990000,41.12,17.185714,10.100000,27.40,9.050,32.6,21.8,33.0
2013-06-04,iq,2013,23,NaN,0.247600,0.296343,0.285371,0.350357,71.52,297.167143,...,45.70,93.891429,71.52,17.448571,9.657143,27.52,10.720,33.8,21.4,68.0
2013-06-11,iq,2013,24,NaN,0.238729,0.251029,0.252586,0.249771,78.96,295.831429,...,45.22,94.967143,78.96,16.410000,7.385714,27.20,10.075,32.6,21.6,93.2
2013-06-18,iq,2013,25,NaN,0.310429,0.302700,0.406614,0.403943,39.54,295.778571,...,4.70,89.057143,39.54,15.137143,8.228571,26.70,8.480,32.2,21.8,34.1
2013-06-25,iq,2013,26,NaN,0.339467,0.240071,0.356943,0.273600,51.80,297.372857,...,27.80,87.030000,51.80,16.148571,11.542857,27.35,9.675,32.6,22.0,14.9

In [50]:
dm = pd.merge((dengue_labels_train),
          (dengue_features_train ), how='right', on='city')

#df1.merge(df2, left_on='lkey', right_on='rkey')

In [51]:
dm

,city,year_x,weekofyear_x,total_cases,year_y,weekofyear_y,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,...,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm
0,sj,1990,18,4,1990,18,1990-04-30,0.122600,0.103725,0.198483,...,32.0,73.365714,12.42,14.012857,2.628571,25.442857,6.9,29.4,20.0,16.0
1,sj,1990,19,5,1990,18,1990-04-30,0.122600,0.103725,0.198483,...,32.0,73.365714,12.42,14.012857,2.628571,25.442857,6.9,29.4,20.0,16.0
2,sj,1990,20,4,1990,18,1990-04-30,0.122600,0.103725,0.198483,...,32.0,73.365714,12.42,14.012857,2.628571,25.442857,6.9,29.4,20.0,16.0
3,sj,1990,21,3,1990,18,1990-04-30,0.122600,0.103725,0.198483,...,32.0,73.365714,12.42,14.012857,2.628571,25.442857,6.9,29.4,20.0,16.0
4,sj,1990,22,6,1990,18,1990-04-30,0.122600,0.103725,0.198483,...,32.0,73.365714,12.42,14.012857,2.628571,25.442857,6.9,29.4,20.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1146491,iq,2010,21,5,2010,25,2010-06-25,0.298186,0.232971,0.274214,...,36.9,89.082857,63.22,17.355714,11.014286,27.475000,9.9,33.7,22.2,20.4
1146492,iq,2010,22,8,2010,25,2010-06-25,0.298186,0.232971,0.274214,...,36.9,89.082857,63.22,17.355714,11.014286,27.475000,9.9,33.7,22.2,20.4
1146493,iq,2010,23,1,2010,25,2010-06-25,0.298186,0.232971,0.274214,...,36.9,89.082857,63.22,17.355714,11.014286,27.475000,9.9,33.7,22.2,20.4
1146494,iq,2010,24,1,2010,25,2010-06-25,0.298186,0.232971,0.274214,...,36.9,89.082857,63.22,17.355714,11.014286,27.475000,9.9,33.7,22.2,20.4
1146495,iq,2010,25,4,2010,25,2010-06-25,0.298186,0.232971,0.274214,...,36.9,89.082857,63.22,17.355714,11.014286,27.475000,9.9,33.7,22.2,20.4

### 1. WRANGLE THE DATA

In [52]:
def wrangle(Filepath):  
    df = pd.merge((dengue_labels_train),
          (dengue_features_train ), how='right', on='city')


    # Drop constant and repeated columns
    df.drop(columns=['ndvi_ne',	'ndvi_nw','ndvi_se'], 
          inplace=True)
  
    # Drop columns with high % of NaN values
    df.dropna(axis=1, thresh=len(df)*.6, inplace=True)
    df.fillna(0, inplace=True)

    return df

In [64]:
df.isnull().sum()

city                                        0
year                                        0
weekofyear                                  0
total_cases                              1872
ndvi_ne                                  1693
ndvi_nw                                  1519
ndvi_se                                  1479
ndvi_sw                                  1479
precipitation_amt_mm                     1471
reanalysis_air_temp_k                    1468
reanalysis_avg_temp_k                    1468
reanalysis_dew_point_temp_k              1468
reanalysis_max_air_temp_k                1468
reanalysis_min_air_temp_k                1468
reanalysis_precip_amt_kg_per_m2          1468
reanalysis_relative_humidity_percent     1468
reanalysis_sat_precip_amt_mm             1471
reanalysis_specific_humidity_g_per_kg    1468
reanalysis_tdtr_k                        1468
station_avg_temp_c                       1511
station_diur_temp_rng_c                  1511
station_max_temp_c                       1479
station_min_temp_c                       1479
station_precip_mm                        1483
dtype: int64

In [67]:
dengue_labels_train.shape
dengue_features_train.shape
df.shape

(3328, 24)

In [54]:
dengue_features_train

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm
0,sj,1990,18,1990-04-30,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,...,32.00,73.365714,12.42,14.012857,2.628571,25.442857,6.900000,29.4,20.0,16.0
1,sj,1990,19,1990-05-07,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,...,17.94,77.368571,22.82,15.372857,2.371429,26.714286,6.371429,31.7,22.2,8.6
2,sj,1990,20,1990-05-14,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,...,26.10,82.052857,34.54,16.848571,2.300000,26.714286,6.485714,32.2,22.8,41.4
3,sj,1990,21,1990-05-21,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,...,13.90,80.337143,15.36,16.672857,2.428571,27.471429,6.771429,33.3,23.3,4.0
4,sj,1990,22,1990-05-28,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,...,12.20,80.460000,7.52,17.210000,3.014286,28.942857,9.371429,35.0,23.9,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1451,iq,2010,21,2010-05-28,0.342750,0.318900,0.256343,0.292514,55.30,299.334286,...,45.00,88.765714,55.30,18.485714,9.800000,28.633333,11.933333,35.4,22.4,27.0
1452,iq,2010,22,2010-06-04,0.160157,0.160371,0.136043,0.225657,86.47,298.330000,...,207.10,91.600000,86.47,18.070000,7.471429,27.433333,10.500000,34.7,21.7,36.6
1453,iq,2010,23,2010-06-11,0.247057,0.146057,0.250357,0.233714,58.94,296.598571,...,50.60,94.280000,58.94,17.008571,7.500000,24.400000,6.900000,32.2,19.2,7.4
1454,iq,2010,24,2010-06-18,0.333914,0.245771,0.278886,0.325486,59.67,296.345714,...,62.33,94.660000,59.67,16.815714,7.871429,25.433333,8.733333,31.2,21.0,16.0
1455,iq,2010,25,2010-06-25,0.298186,0.232971,0.274214,0.315757,63.22,298.097143,...,36.90,89.082857,63.22,17.355714,11.014286,27.475000,9.900000,33.7,22.2,20.4

In [55]:
dengue_features_train['city']

0       sj
1       sj
2       sj
3       sj
4       sj
        ..
1451    iq
1452    iq
1453    iq
1454    iq
1455    iq
Name: city, Length: 1456, dtype: object

In [56]:
mask = dengue_features_train['city']=='sj'

In [57]:
dengue_features_train[mask]

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm
0,sj,1990,18,1990-04-30,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,...,32.00,73.365714,12.42,14.012857,2.628571,25.442857,6.900000,29.4,20.0,16.0
1,sj,1990,19,1990-05-07,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,...,17.94,77.368571,22.82,15.372857,2.371429,26.714286,6.371429,31.7,22.2,8.6
2,sj,1990,20,1990-05-14,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,...,26.10,82.052857,34.54,16.848571,2.300000,26.714286,6.485714,32.2,22.8,41.4
3,sj,1990,21,1990-05-21,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,...,13.90,80.337143,15.36,16.672857,2.428571,27.471429,6.771429,33.3,23.3,4.0
4,sj,1990,22,1990-05-28,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,...,12.20,80.460000,7.52,17.210000,3.014286,28.942857,9.371429,35.0,23.9,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
931,sj,2008,13,2008-03-25,0.077850,-0.039900,0.310471,0.296243,27.19,296.958571,...,7.55,74.247143,27.19,13.644286,2.885714,25.042857,5.785714,30.0,21.1,1.8
932,sj,2008,14,2008-04-01,-0.038000,-0.016833,0.119371,0.066386,3.82,298.081429,...,3.67,74.600000,3.82,14.662857,2.714286,26.242857,6.814286,30.6,22.2,0.5
933,sj,2008,15,2008-04-08,-0.155200,-0.052750,0.137757,0.141214,16.96,297.460000,...,35.00,75.027143,16.96,14.184286,2.185714,25.000000,5.714286,29.4,21.7,30.7
934,sj,2008,16,2008-04-15,0.001800,NaN,0.203900,0.209843,0.00,297.630000,...,4.82,72.285714,0.00,13.858571,2.785714,25.314286,6.242857,29.4,21.7,11.2
935,sj,2008,17,2008-04-22,-0.037000,-0.010367,0.077314,0.090586,0.00,298.672857,...,2.17,76.960000,0.00,15.671429,3.957143,27.042857,7.514286,31.7,23.3,0.3

### SPLIT THE DATA

In [58]:
# Split our feature matrix and target vector
y = df['total_cases']
X = df.drop('total_cases', axis=1)

In [59]:
# Train-validation split
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

### ESTABLISH A BASELINE

In [60]:
#print('Baseline Accuracy Score:', y_train.value_counts(normalize=True).max())

In [61]:
from sklearn.metrics import mean_absolute_error
print('total_cases:', y_train.mean())
y_pred = [y_train.mean()] * len(y_train)
print('Baseline MAE:', mean_absolute_error(y_train, y_pred))

total_cases: 24.15641476274165

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [62]:
#y_train.dtypes
y_train.isnull().sum()
#len(y_train)

1524

### BUILD THE MODEL

In [ ]:
model_rf = make_pipeline(OrdinalEncoder(),
                        SimpleImputer(strategy='median'),
                        RandomForestClassifier(random_state=42))
model_rf.fit(X_train, y_train)

In [ ]:
print('base model accuracy is', model_rf.score(X_val, y_val))

In [ ]:
model_gb = make_pipeline(OrdinalEncoder(),
                        SimpleImputer(strategy='median'),
                        GradientBoostingClassifier(learning_rate=0.1, n_estimators=150, random_state=42))
model_gb.fit(X_train, y_train)

In [ ]:
model_xg

In [ ]:
print('XGBoosting model accuracy is', model_xg.score(X_val, y_val))

### CHECK THE METRICS

In [ ]:
#Mean_Absolute_Error
print('Training MAE:', mean_absolute_error(y_train, model.predict(X_train)))
print('Test MAE:', mean_absolute_error(y_test, model.predict(X_test)))

In [ ]:
#Root_Mean_Squared_Error

In [ ]:
print('Training MAE:', mean_squared_error(y_train, model.predict(X_train), squared=False))
print('Test MAE:', mean_squared_error(y_test, model.predict(X_test), squared=False))

In [ ]:
R2score

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_train,model.predict(X_train))

### TUNE THE MODEL

### RESULTS OF THE FINIDINGS

#Feature Importances

In [ ]:
importances = model_xg.named_steps['xgbclassifier'].feature_importances_
features = X_train.columns

feat_imp = pd.Series(importances, index=features).sort_values()
feat_imp.tail(10).plot(kind='barh')
plt.xlabel('Gini Importance')
plt.ylabel('Feature')
plt.title('Feature Importances for model_xg');

#Permutation Impotances

In [ ]:
perm_imp = permutation_importance(model_xg,
                                  X_val, 
                                  y_val, 
                                  n_jobs=10, 
                                  random_state=42)

In [ ]:
perm_imp

In [ ]:
perm_imp['importances_mean']

In [ ]:
data = pd.DataFrame({'importances_mean': perm_imp['importances_mean']}, index = X_val.columns)

In [ ]:
data['importances_mean'].sort_values().tail(10).plot(kind='barh')
plt.xlabel('Permutation Importance')
plt.ylabel('Feature')
plt.title('Feature Importances for model_xg');

### SUBMISSION